In [2]:
import numpy as np
import pandas as pd

In [5]:
A = np.random.randint(5, size=(10,2))

In [6]:
A

array([[2, 4],
       [1, 0],
       [1, 3],
       [4, 1],
       [3, 3],
       [1, 4],
       [1, 4],
       [4, 2],
       [4, 3],
       [2, 4]])

In [7]:
A[0:,]

array([[2, 4],
       [1, 0],
       [1, 3],
       [4, 1],
       [3, 3],
       [1, 4],
       [1, 4],
       [4, 2],
       [4, 3],
       [2, 4]])

In [8]:
A[0]

array([2, 4])

In [9]:
A[0:]

array([[2, 4],
       [1, 0],
       [1, 3],
       [4, 1],
       [3, 3],
       [1, 4],
       [1, 4],
       [4, 2],
       [4, 3],
       [2, 4]])

In [11]:
A[0,:]

array([2, 4])