In [2]:
import pandas as pd
import numpy as np
from numpy import genfromtxt

file_path = '../../datasets/basic/Istanbul.csv'

data = pd.read_csv(file_path)
data = data.select_dtypes(include=[np.number])
data = np.array(data)
data

array([[ 0.03575371,  0.03837619, -0.00467931, ...,  0.03119023,
         0.01269804,  0.02852446],
       [ 0.02542587,  0.03181274,  0.00778674, ...,  0.01891958,
         0.01134065,  0.00877264],
       [-0.02886173, -0.02635297, -0.03046913, ..., -0.03589858,
        -0.0170728 , -0.02001541],
       ..., 
       [ 0.00019097, -0.0016526 ,  0.00192291, ...,  0.00562792,
         0.00057157,  0.00693787],
       [-0.01306904, -0.01370599, -0.02074215, ..., -0.01194168,
        -0.01261533, -0.00095774],
       [-0.00724632, -0.01944185,  0.        , ..., -0.01225155,
        -0.00546489, -0.01429693]])

In [4]:
dataX = data[:, 0:-1]
dataX[1:5]

array([[ 0.02542587,  0.03181274,  0.00778674,  0.00845534,  0.01286561,
         0.00416245,  0.01891958,  0.01134065],
       [-0.02886173, -0.02635297, -0.03046913, -0.01783306, -0.02873459,
         0.01729293, -0.03589858, -0.0170728 ],
       [-0.06220808, -0.0847159 ,  0.00339136, -0.01172628, -0.000466  ,
        -0.04006131,  0.02828315, -0.00556096],
       [ 0.00985991,  0.00965811, -0.02153321, -0.01987275, -0.01270972,
        -0.0044735 , -0.00976388, -0.01098863]])

In [12]:
dataY = data[:, -1]
dataY

array([  2.85244620e-02,   8.77264400e-03,  -2.00154120e-02,
        -1.94237780e-02,  -7.80221200e-03,  -2.26297450e-02,
        -4.82713800e-03,  -8.67664600e-03,  -2.34287290e-02,
         1.09168930e-02,  -4.02900400e-03,  -2.41071930e-02,
        -5.09224200e-03,  -3.22724900e-03,  -8.07731900e-03,
         1.03196850e-02,   6.34449800e-03,   2.21041030e-02,
         4.08697000e-04,   2.24253900e-03,  -1.90913850e-02,
         1.27186860e-02,   1.51655890e-02,   2.07250500e-03,
         3.23381140e-02,   7.89539400e-03,  -2.13909500e-03,
        -7.92599700e-03,  -1.47727480e-02,   1.77644440e-02,
        -6.85044100e-03,  -3.83227710e-02,  -3.34226100e-03,
         6.76449800e-03,  -2.72944420e-02,   9.67787000e-03,
        -1.18811120e-02,   6.09936400e-03,  -2.33116400e-03,
        -6.15013100e-03,  -3.53648820e-02,   1.29030700e-03,
         3.03115060e-02,  -8.67183800e-03,  -2.09764700e-03,
        -5.55836400e-03,   2.49099540e-02,   1.28157200e-02,
         5.41947500e-03,

In [13]:
dataY1 = dataY.reshape((dataX.shape[0], 1))

In [14]:
dataY1

array([[  2.85244620e-02],
       [  8.77264400e-03],
       [ -2.00154120e-02],
       [ -1.94237780e-02],
       [ -7.80221200e-03],
       [ -2.26297450e-02],
       [ -4.82713800e-03],
       [ -8.67664600e-03],
       [ -2.34287290e-02],
       [  1.09168930e-02],
       [ -4.02900400e-03],
       [ -2.41071930e-02],
       [ -5.09224200e-03],
       [ -3.22724900e-03],
       [ -8.07731900e-03],
       [  1.03196850e-02],
       [  6.34449800e-03],
       [  2.21041030e-02],
       [  4.08697000e-04],
       [  2.24253900e-03],
       [ -1.90913850e-02],
       [  1.27186860e-02],
       [  1.51655890e-02],
       [  2.07250500e-03],
       [  3.23381140e-02],
       [  7.89539400e-03],
       [ -2.13909500e-03],
       [ -7.92599700e-03],
       [ -1.47727480e-02],
       [  1.77644440e-02],
       [ -6.85044100e-03],
       [ -3.83227710e-02],
       [ -3.34226100e-03],
       [  6.76449800e-03],
       [ -2.72944420e-02],
       [  9.67787000e-03],
       [ -1.18811120e-02],
 

In [23]:
dataY2 = np.vstack((dataY))
dataY2

array([[  2.85244620e-02],
       [  8.77264400e-03],
       [ -2.00154120e-02],
       [ -1.94237780e-02],
       [ -7.80221200e-03],
       [ -2.26297450e-02],
       [ -4.82713800e-03],
       [ -8.67664600e-03],
       [ -2.34287290e-02],
       [  1.09168930e-02],
       [ -4.02900400e-03],
       [ -2.41071930e-02],
       [ -5.09224200e-03],
       [ -3.22724900e-03],
       [ -8.07731900e-03],
       [  1.03196850e-02],
       [  6.34449800e-03],
       [  2.21041030e-02],
       [  4.08697000e-04],
       [  2.24253900e-03],
       [ -1.90913850e-02],
       [  1.27186860e-02],
       [  1.51655890e-02],
       [  2.07250500e-03],
       [  3.23381140e-02],
       [  7.89539400e-03],
       [ -2.13909500e-03],
       [ -7.92599700e-03],
       [ -1.47727480e-02],
       [  1.77644440e-02],
       [ -6.85044100e-03],
       [ -3.83227710e-02],
       [ -3.34226100e-03],
       [  6.76449800e-03],
       [ -2.72944420e-02],
       [  9.67787000e-03],
       [ -1.18811120e-02],
 