In [1]:
# https://campus.datacamp.com/courses/intro-to-python-for-data-science/chapter-4-numpy?ex=1

import numpy as np

height = [1,2,3,4,5,6]
np_height = np.array(height)

weight = [1,2,3,4,5,6]
np_weight = np.array(weight)

x = np_height * np_weight

x

array([ 1,  4,  9, 16, 25, 36])

In [3]:
x > 10

array([False, False, False,  True,  True,  True], dtype=bool)

In [6]:
type(x)

numpy.ndarray

In [7]:
np_2d = np.array([[1.73, 1.65, 12.32, 123.3, 2.123], [12.3, 213.3, 32.32, 1.12, 23.2]])

In [8]:
np_2d

array([[   1.73 ,    1.65 ,   12.32 ,  123.3  ,    2.123],
       [  12.3  ,  213.3  ,   32.32 ,    1.12 ,   23.2  ]])

In [9]:
np_2d[0]

array([   1.73 ,    1.65 ,   12.32 ,  123.3  ,    2.123])

In [10]:
np_2d[1]

array([  12.3 ,  213.3 ,   32.32,    1.12,   23.2 ])

In [12]:
np_2d[0, 2]

12.32

In [13]:
np_2d[0][2]

12.32

In [15]:
np_2d[:, 1:3]

array([[   1.65,   12.32],
       [ 213.3 ,   32.32]])

In [16]:
np_2d[1, :]

array([  12.3 ,  213.3 ,   32.32,    1.12,   23.2 ])

In [17]:
np_2d.shape

(2, 5)

In [20]:
np_2d[:, :3]

array([[   1.73,    1.65,   12.32],
       [  12.3 ,  213.3 ,   32.32]])

In [21]:
np_2d[:, 2]

array([ 12.32,  32.32])

In [22]:
x = ["a", "b", "c"]

In [23]:
x

['a', 'b', 'c']

In [24]:
del(x[1])

In [25]:
x

['a', 'c']

In [26]:
x + ["what"]

['a', 'c', 'what']

In [29]:
height = np.round(np.random.normal(1.75, 0.20, 5000), 2)
weight = np.round(np.random.normal(60.32, 15, 5000), 2)
np_city = np.column_stack((height, weight))

In [30]:
np_city

array([[  1.5 ,  52.17],
       [  1.7 ,  41.25],
       [  1.57,  13.3 ],
       ..., 
       [  2.05,  71.45],
       [  1.71,  36.74],
       [  1.69,  48.82]])

In [33]:
np.mean(np_city[:, 0])

1.7490680000000001

In [34]:
np.median(np_city[:, 0])

1.75

In [37]:
np.corrcoef(np_city[:, 0], np_city[:, 1])

array([[ 1.       , -0.0034975],
       [-0.0034975,  1.       ]])

In [38]:
np.std(np_city[:, 0])

0.19933070856242896