In [1]:
# https://campus.datacamp.com/courses/intro-to-python-for-data-science/chapter-4-numpy?ex=1

import numpy as np

height = [1,2,3,4,5,6]
np_height = np.array(height)

weight = [1,2,3,4,5,6]
np_weight = np.array(weight)

x = np_height * np_weight

x

array([ 1,  4,  9, 16, 25, 36])

In [3]:
x > 10

array([False, False, False,  True,  True,  True], dtype=bool)

In [4]:
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])