In [15]:
import numpy as np

In [16]:
ones = np.ones((5, 10))

In [17]:
ones

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [18]:
zeros = np.zeros((10, 3))

In [19]:
zeros

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [27]:
rn = np.random.rand(4,2)

In [30]:
rn

array([[ 0.9286841 ,  0.57860959],
       [ 0.33037324,  0.0241182 ],
       [ 0.76816983,  0.85176503],
       [ 0.74379406,  0.87081149]])

In [31]:
random_normal = np.random.normal(size=(2,3))

In [32]:
random_normal

array([[ 0.28461764,  1.11601027,  0.30418766],
       [ 1.86855267, -1.44468068,  0.41024676]])

In [34]:
random_std = np.random.normal(50, 10, size=(2,3))

In [35]:
random_std

array([[ 50.49962281,  40.45019081,  70.54543302],
       [ 59.33021475,  57.93023901,  45.96795843]])

In [38]:
b = np.random.rand(10,5)

In [39]:
b

array([[ 0.5826061 ,  0.95072673,  0.48933609,  0.22407663,  0.76595772],
       [ 0.14793564,  0.3881113 ,  0.85668027,  0.28369417,  0.54083175],
       [ 0.26282468,  0.31344552,  0.89805603,  0.84218534,  0.56607202],
       [ 0.67575148,  0.50407333,  0.63193639,  0.38494354,  0.17938791],
       [ 0.30495215,  0.66172096,  0.86358215,  0.52025755,  0.69860345],
       [ 0.44347538,  0.59269422,  0.30850779,  0.52690193,  0.37422277],
       [ 0.25274374,  0.50083853,  0.30917301,  0.6325534 ,  0.02546144],
       [ 0.38921894,  0.21353529,  0.54897438,  0.67231372,  0.38442323],
       [ 0.04274398,  0.2657795 ,  0.58226071,  0.6203209 ,  0.29788147],
       [ 0.46194767,  0.84948072,  0.75323331,  0.0226394 ,  0.77615871]])

In [40]:
c = b.sum(axis=0)
c

array([ 3.56419975,  5.24040611,  6.24174015,  4.72988659,  4.60900047])

In [41]:
d = b.sum(axis=1)

In [42]:
d

array([ 3.01270327,  2.21725314,  2.88258359,  2.37609265,  3.04911626,
        2.24580209,  1.72077013,  2.20846556,  1.80898656,  2.86345982])