In [3]:
import numpy as np

In [4]:
my_3d_array = np.arange(70)
my_3d_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69])

In [5]:
my_3d_array.shape = (2,7,5)

In [6]:
my_3d_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [7]:
my_3d_array.shape

(2, 7, 5)

In [8]:
my_3d_array.ndim

3

In [9]:
my_3d_array.size

70

In [10]:
my_3d_array.dtype

dtype('int64')

In [11]:
5 * my_3d_array -2 

array([[[ -2,   3,   8,  13,  18],
        [ 23,  28,  33,  38,  43],
        [ 48,  53,  58,  63,  68],
        [ 73,  78,  83,  88,  93],
        [ 98, 103, 108, 113, 118],
        [123, 128, 133, 138, 143],
        [148, 153, 158, 163, 168]],

       [[173, 178, 183, 188, 193],
        [198, 203, 208, 213, 218],
        [223, 228, 233, 238, 243],
        [248, 253, 258, 263, 268],
        [273, 278, 283, 288, 293],
        [298, 303, 308, 313, 318],
        [323, 328, 333, 338, 343]]])

In [12]:
left_mat = np.arange(6).reshape((2,3))
left_mat

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
right_mat = np.arange(15).reshape((3,5))
right_mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
m = np.dot(left_mat, right_mat)

In [15]:
m.sum()

625

In [16]:
m.sum(axis=1)

array([155, 470])

In [17]:
m.sum(axis=0)

array([ 95, 110, 125, 140, 155])

In [18]:
my_2d_array = np.ones(35, dtype="int_").reshape((7,5)) * 3
my_2d_array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [19]:
my_random_2d = np.random.random((7,5))
my_random_2d

array([[ 0.33462135,  0.52376163,  0.20623562,  0.51413186,  0.76757325],
       [ 0.31897857,  0.98671706,  0.42377832,  0.09178044,  0.83798314],
       [ 0.91390148,  0.43583504,  0.06664066,  0.23975838,  0.14829872],
       [ 0.15589411,  0.19223827,  0.35611536,  0.71437795,  0.89578772],
       [ 0.69763986,  0.81932045,  0.23305733,  0.92767333,  0.88515783],
       [ 0.73665754,  0.91306461,  0.22150083,  0.64366625,  0.38350384],
       [ 0.38868087,  0.07319889,  0.95558052,  0.91868782,  0.53716398]])

In [20]:
np.set_printoptions(precision=4)
my_2d_array * my_random_2d

array([[ 1.0039,  1.5713,  0.6187,  1.5424,  2.3027],
       [ 0.9569,  2.9602,  1.2713,  0.2753,  2.5139],
       [ 2.7417,  1.3075,  0.1999,  0.7193,  0.4449],
       [ 0.4677,  0.5767,  1.0683,  2.1431,  2.6874],
       [ 2.0929,  2.458 ,  0.6992,  2.783 ,  2.6555],
       [ 2.21  ,  2.7392,  0.6645,  1.931 ,  1.1505],
       [ 1.166 ,  0.2196,  2.8667,  2.7561,  1.6115]])