In [1]:
import numpy as np

In [2]:
# vstack
np.vstack(([1,2,3], [4,5,6]))

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
# column_stack
np.column_stack(([1,2,3], [4,5,6]))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [11]:
# hstack
np.hstack(([1,2,3], [3,4,5]))

array([1, 2, 3, 3, 4, 5])

In [19]:
a = [[1,2,3], [4,5,6]]

In [20]:
a

[[1, 2, 3], [4, 5, 6]]

In [21]:
a[1,1]

TypeError: list indices must be integers or slices, not tuple

In [22]:
a(1,1)

TypeError: 'list' object is not callable

In [25]:
a[1:0]

[]

In [26]:
a[0:2]

[[1, 2, 3], [4, 5, 6]]

In [27]:
a[0:1]

[[1, 2, 3]]

In [28]:
a[0][1]

2

In [29]:
a[0,1]

TypeError: list indices must be integers or slices, not tuple

In [30]:
a[(0,1)]

TypeError: list indices must be integers or slices, not tuple