In [1]:
import numpy as np

In [2]:
# vstack
np.vstack(([1,2,3], [4,5,6]))

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
# column_stack
np.column_stack(([1,2,3], [4,5,6]))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [4]:
# hstack
np.hstack(([1,2,3], [3,4,5]))

array([1, 2, 3, 3, 4, 5])