In [6]:
import numpy as np

In [7]:
a = np.random.uniform(size=(10, 5))

In [8]:
a

array([[ 0.26898079,  0.6507571 ,  0.72383543,  0.1957662 ,  0.35611194],
       [ 0.24448345,  0.15923186,  0.09575959,  0.85642007,  0.32795479],
       [ 0.80685588,  0.43697584,  0.5496483 ,  0.64375503,  0.98291764],
       [ 0.76603336,  0.53266504,  0.89468355,  0.34315829,  0.88685919],
       [ 0.54841885,  0.8643471 ,  0.11160412,  0.46168351,  0.77800723],
       [ 0.40440131,  0.13839757,  0.68496954,  0.95629333,  0.44515265],
       [ 0.70406361,  0.44503504,  0.08022634,  0.64746339,  0.67365112],
       [ 0.16421701,  0.11167228,  0.28149271,  0.90226458,  0.44299269],
       [ 0.98243547,  0.20308128,  0.98376525,  0.71807326,  0.32974658],
       [ 0.73730065,  0.99952561,  0.68238685,  0.01125393,  0.35732673]])

In [9]:
a[1,1]

0.15923186464365002

In [10]:
a[0,0]

0.26898079015683996

In [11]:
a[0, -1]

0.35611193634504579

In [12]:
a[0,:]

array([ 0.26898079,  0.6507571 ,  0.72383543,  0.1957662 ,  0.35611194])

In [13]:
a[2:4, 1]

array([ 0.43697584,  0.53266504])

In [14]:
a[2, 1:3]

array([ 0.43697584,  0.5496483 ])

In [15]:
a[a < 0.5] = 100

In [16]:
a

array([[ 100.        ,    0.6507571 ,    0.72383543,  100.        ,  100.        ],
       [ 100.        ,  100.        ,  100.        ,    0.85642007,  100.        ],
       [   0.80685588,  100.        ,    0.5496483 ,    0.64375503,
           0.98291764],
       [   0.76603336,    0.53266504,    0.89468355,  100.        ,
           0.88685919],
       [   0.54841885,    0.8643471 ,  100.        ,  100.        ,
           0.77800723],
       [ 100.        ,  100.        ,    0.68496954,    0.95629333,  100.        ],
       [   0.70406361,  100.        ,  100.        ,    0.64746339,
           0.67365112],
       [ 100.        ,  100.        ,  100.        ,    0.90226458,  100.        ],
       [   0.98243547,  100.        ,    0.98376525,    0.71807326,  100.        ],
       [   0.73730065,    0.99952561,    0.68238685,  100.        ,  100.        ]])

In [17]:
one = np.random.uniform(size=(3,2))

In [18]:
two = np.random.uniform(size=(3,2))

In [19]:
one

array([[ 0.5434533 ,  0.02401615],
       [ 0.90584521,  0.56829129],
       [ 0.83687915,  0.96920792]])

In [20]:
two

array([[ 0.67242365,  0.9827171 ],
       [ 0.7303139 ,  0.1143603 ],
       [ 0.75834743,  0.73378914]])

In [21]:
one[two < 0.5] = -1

In [22]:
one

array([[ 0.5434533 ,  0.02401615],
       [ 0.90584521, -1.        ],
       [ 0.83687915,  0.96920792]])

In [24]:
one[1, 1]

-1.0

In [26]:
# 3d
a_3d = np.arange(70)
a_3d.shape = (2,7,5)
a_3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])