In [1]:
import numpy as np

In [13]:
a = np.random.uniform(size=(10, 5))

In [14]:
a

array([[ 0.50610192,  0.86896471,  0.38190261,  0.71401392,  0.93096976],
       [ 0.17926019,  0.45374751,  0.95256788,  0.05878559,  0.12010502],
       [ 0.85353691,  0.24993598,  0.14063317,  0.64846646,  0.40409039],
       [ 0.05790715,  0.97189713,  0.31661762,  0.59039009,  0.12241594],
       [ 0.23420784,  0.31755396,  0.38322432,  0.79740684,  0.60478535],
       [ 0.12255639,  0.47945496,  0.42949319,  0.22469487,  0.14908483],
       [ 0.51826073,  0.03357086,  0.47101876,  0.5128335 ,  0.79201529],
       [ 0.53799923,  0.61338769,  0.23684674,  0.20459728,  0.6218164 ],
       [ 0.7787664 ,  0.91105991,  0.55598439,  0.26240593,  0.33542143],
       [ 0.50752841,  0.80376421,  0.97703512,  0.12807028,  0.54709168]])

In [16]:
a[1,1]

0.45374750518747986

In [17]:
a[0,0]

0.50610192366780637

In [20]:
a[0, -1]

0.93096976074473847

In [23]:
a[0,:]

array([ 0.50610192,  0.86896471,  0.38190261,  0.71401392,  0.93096976])

In [30]:
a[2:4, 1]

array([ 0.24993598,  0.97189713])

In [29]:
a[2, 1:3]

array([ 0.24993598,  0.14063317])

In [31]:
a[a < 0.5] = 100

In [32]:
a

array([[   0.50610192,    0.86896471,  100.        ,    0.71401392,
           0.93096976],
       [ 100.        ,  100.        ,    0.95256788,  100.        ,  100.        ],
       [   0.85353691,  100.        ,  100.        ,    0.64846646,  100.        ],
       [ 100.        ,    0.97189713,  100.        ,    0.59039009,  100.        ],
       [ 100.        ,  100.        ,  100.        ,    0.79740684,
           0.60478535],
       [ 100.        ,  100.        ,  100.        ,  100.        ,  100.        ],
       [   0.51826073,  100.        ,  100.        ,    0.5128335 ,
           0.79201529],
       [   0.53799923,    0.61338769,  100.        ,  100.        ,
           0.6218164 ],
       [   0.7787664 ,    0.91105991,    0.55598439,  100.        ,  100.        ],
       [   0.50752841,    0.80376421,    0.97703512,  100.        ,
           0.54709168]])

In [33]:
one = np.random.uniform(size=(3,2))

In [34]:
two = np.random.uniform(size=(3,2))

In [35]:
one

array([[ 0.25553977,  0.17421019],
       [ 0.50567967,  0.8707095 ],
       [ 0.20316233,  0.92985828]])

In [36]:
two

array([[ 0.87576521,  0.11194237],
       [ 0.72248321,  0.60858552],
       [ 0.67787691,  0.62713406]])

In [38]:
one[two < 0.5] = -1

In [39]:
one

array([[ 0.25553977, -1.        ],
       [ 0.50567967,  0.8707095 ],
       [ 0.20316233,  0.92985828]])