In [2]:
import numpy as np
import scipy as sp
import cv2

In [7]:
corners = np.zeros((4,1,2), dtype=np.float32)

In [8]:
print(corners)

[[[ 0.  0.]]

 [[ 0.  0.]]

 [[ 0.  0.]]

 [[ 0.  0.]]]


In [10]:
print(corners.ndim)

3


In [11]:
print(corners.size)

8


In [12]:
print(corners.dtype)

float32


In [13]:
corners

array([[[ 0.,  0.]],

       [[ 0.,  0.]],

       [[ 0.,  0.]],

       [[ 0.,  0.]]], dtype=float32)

In [14]:
corners.sum()

0.0

In [15]:
np.squeeze(corners)

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]], dtype=float32)